//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAssistant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAssistant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化完毕.等待写入数据文件.
        /// </summary>
        internal static string frmInstall_frmInstall_Shown_初始化完毕_等待写入数据文件 {
            get {
                return ResourceManager.GetString("frmInstall_frmInstall_Shown_初始化完毕_等待写入数据文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有操作全部完毕.
        /// </summary>
        internal static string frmInstall_frmInstall_Shown_所有操作全部完毕 {
            get {
                return ResourceManager.GetString("frmInstall_frmInstall_Shown_所有操作全部完毕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据文件写入完毕,等待配置.
        /// </summary>
        internal static string frmInstall_frmInstall_Shown_数据文件写入完毕_等待配置 {
            get {
                return ResourceManager.GetString("frmInstall_frmInstall_Shown_数据文件写入完毕_等待配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在为32位系统初始化..
        /// </summary>
        internal static string frmInstall_frmInstall_Shown_正在为32位系统初始化_ {
            get {
                return ResourceManager.GetString("frmInstall_frmInstall_Shown_正在为32位系统初始化_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在为64位系统初始化..
        /// </summary>
        internal static string frmInstall_frmInstall_Shown_正在为64位系统初始化_ {
            get {
                return ResourceManager.GetString("frmInstall_frmInstall_Shown_正在为64位系统初始化_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在写入数据文件.
        /// </summary>
        internal static string frmInstall_frmInstall_Shown_正在写入数据文件 {
            get {
                return ResourceManager.GetString("frmInstall_frmInstall_Shown_正在写入数据文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在判别操作系统版本..
        /// </summary>
        internal static string frmInstall_frmInstall_Shown_正在判别操作系统版本_ {
            get {
                return ResourceManager.GetString("frmInstall_frmInstall_Shown_正在判别操作系统版本_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统初始化结束.
        /// </summary>
        internal static string frmInstall_frmInstall_Shown_系统初始化结束 {
            get {
                return ResourceManager.GetString("frmInstall_frmInstall_Shown_系统初始化结束", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请等待完成.
        /// </summary>
        internal static string frmInstall_frmInstall_Shown_请等待完成 {
            get {
                return ResourceManager.GetString("frmInstall_frmInstall_Shown_请等待完成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置完毕.
        /// </summary>
        internal static string frmInstall_frmInstall_Shown_配置完毕 {
            get {
                return ResourceManager.GetString("frmInstall_frmInstall_Shown_配置完毕", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string frmInstall_installBaseSQL__ {
            get {
                return ResourceManager.GetString("frmInstall_installBaseSQL__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  --- .
        /// </summary>
        internal static string frmInstall_installBaseSQL______ {
            get {
                return ResourceManager.GetString("frmInstall_installBaseSQL______", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在安装基础包.
        /// </summary>
        internal static string frmInstall_installBaseSQL_正在安装基础包 {
            get {
                return ResourceManager.GetString("frmInstall_installBaseSQL_正在安装基础包", resourceCulture);
            }
        }
    }
}
