//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LongXiangTutorialController.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LongXiangTutorialController.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Back {
            get {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cdrom_mount {
            get {
                object obj = ResourceManager.GetObject("cdrom_mount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择一个目录用以保存常用软件,程序将自动生成子目录! 请注意,该选择在重新安装服务前,无法更改.手动修改该目录将会导致严重的后果!.
        /// </summary>
        internal static string frmInstallService_cmdSelect_Click_选择一个目录用以保存常用软件_程序将自动生成子目录__请注意_该选择在重新安装服务前_无法更改_手动修改该目录将会导致严重的后果_ {
            get {
                return ResourceManager.GetString("frmInstallService_cmdSelect_Click_选择一个目录用以保存常用软件_程序将自动生成子目录__请注意_该选择在重新安装服务前_无法更改" +
                        "_手动修改该目录将会导致严重的后果_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除该软件失败,错误原因:
        ///!.
        /// </summary>
        internal static string frmSoftware_cmdDelete_Click_ {
            get {
                return ResourceManager.GetString("frmSoftware_cmdDelete_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除该软件成功!.
        /// </summary>
        internal static string frmSoftware_cmdDelete_Click_删除该软件成功_ {
            get {
                return ResourceManager.GetString("frmSoftware_cmdDelete_Click_删除该软件成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询龙翔常用软件数据错误!.
        /// </summary>
        internal static string frmSoftware_cmdView_Click_查询龙翔常用软件数据错误_ {
            get {
                return ResourceManager.GetString("frmSoftware_cmdView_Click_查询龙翔常用软件数据错误_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除该教程失败,错误原因:
        ///!.
        /// </summary>
        internal static string frmTutorial_cmdDel_Click_ {
            get {
                return ResourceManager.GetString("frmTutorial_cmdDel_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除该教程成功!.
        /// </summary>
        internal static string frmTutorial_cmdDel_Click_删除该教程成功_ {
            get {
                return ResourceManager.GetString("frmTutorial_cmdDel_Click_删除该教程成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询龙翔教程数据错误!.
        /// </summary>
        internal static string frmTutorial_cmdSearch_Click_查询龙翔教程数据错误_ {
            get {
                return ResourceManager.GetString("frmTutorial_cmdSearch_Click_查询龙翔教程数据错误_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap install {
            get {
                object obj = ResourceManager.GetObject("install", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap internet_networking {
            get {
                object obj = ResourceManager.GetObject("internet&networking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误的参数! 请从龙翔启动控制器中启动本程序!.
        /// </summary>
        internal static string Program_Main_错误的参数__请从龙翔启动控制器中启动本程序_ {
            get {
                return ResourceManager.GetString("Program_Main_错误的参数__请从龙翔启动控制器中启动本程序_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Service_Manager {
            get {
                object obj = ResourceManager.GetObject("Service Manager", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap web {
            get {
                object obj = ResourceManager.GetObject("web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
