//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LongXiangTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LongXiangTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _123 {
            get {
                object obj = ResourceManager.GetObject("123", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ajax_loader1 {
            get {
                object obj = ResourceManager.GetObject("ajax-loader1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ajax_loader3 {
            get {
                object obj = ResourceManager.GetObject("ajax-loader3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  -.
        /// </summary>
        internal static string frmBatchPrices_cmdUpdate_Click___ {
            get {
                return ResourceManager.GetString("frmBatchPrices_cmdUpdate_Click___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 递交价格报表失败,失败原因:/r/n.
        /// </summary>
        internal static string frmBatchPrices_cmdUpdate_Click_递交价格报表失败_失败原因__r_n {
            get {
                return ResourceManager.GetString("frmBatchPrices_cmdUpdate_Click_递交价格报表失败_失败原因__r_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 递交价格报表成功.
        /// </summary>
        internal static string frmBatchPrices_cmdUpdate_Click_递交价格报表成功 {
            get {
                return ResourceManager.GetString("frmBatchPrices_cmdUpdate_Click_递交价格报表成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 价格.
        /// </summary>
        internal static string frmBatchPrices_frmBatchPrices_Load_价格 {
            get {
                return ResourceManager.GetString("frmBatchPrices_frmBatchPrices_Load_价格", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库访问异常,请关闭后重试!.
        /// </summary>
        internal static string frmBatchPrices_frmBatchPrices_Load_数据库访问异常_请关闭后重试_ {
            get {
                return ResourceManager.GetString("frmBatchPrices_frmBatchPrices_Load_数据库访问异常_请关闭后重试_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 机型.
        /// </summary>
        internal static string frmBatchPrices_frmBatchPrices_Load_机型 {
            get {
                return ResourceManager.GetString("frmBatchPrices_frmBatchPrices_Load_机型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色产地.
        /// </summary>
        internal static string frmBatchPrices_frmBatchPrices_Load_颜色产地 {
            get {
                return ResourceManager.GetString("frmBatchPrices_frmBatchPrices_Load_颜色产地", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  V:.
        /// </summary>
        internal static string frmLogin_frmLogin_Load__V_ {
            get {
                return ResourceManager.GetString("frmLogin_frmLogin_Load__V_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Database (Windows 7下请确认目录可写).
        /// </summary>
        internal static string frmOther_cmdBackupDB_Click_Backup_Database {
            get {
                return ResourceManager.GetString("frmOther_cmdBackupDB_Click_Backup_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Dump|*.sql.
        /// </summary>
        internal static string frmOther_cmdBackupDB_Click_SQL_Dump___sql {
            get {
                return ResourceManager.GetString("frmOther_cmdBackupDB_Click_SQL_Dump___sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备份数据库完毕,请检查!.
        /// </summary>
        internal static string frmOther_cmdBackupDB_Click_请等待一会CMD窗体完成后检视SQL文件 {
            get {
                return ResourceManager.GetString("frmOther_cmdBackupDB_Click_请等待一会CMD窗体完成后检视SQL文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 核查网站市场价格失败! 错误原因:.
        /// </summary>
        internal static string frmOther_cmdCheckMarketPrice_Click_核查网站市场价格失败__错误原因_ {
            get {
                return ResourceManager.GetString("frmOther_cmdCheckMarketPrice_Click_核查网站市场价格失败__错误原因_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 核查网站市场价格成功!.
        /// </summary>
        internal static string frmOther_cmdCheckMarketPrice_Click_核查网站市场价格成功_ {
            get {
                return ResourceManager.GetString("frmOther_cmdCheckMarketPrice_Click_核查网站市场价格成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新网站缓存完毕!.
        /// </summary>
        internal static string frmOther_cmdCleanSCache_Click_更新网站缓存完毕_ {
            get {
                return ResourceManager.GetString("frmOther_cmdCleanSCache_Click_更新网站缓存完毕_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新手机大全缓存完毕!.
        /// </summary>
        internal static string frmOther_cmdClearECache_Click_更新手机大全缓存完毕_ {
            get {
                return ResourceManager.GetString("frmOther_cmdClearECache_Click_更新手机大全缓存完毕_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 核查网站新闻失败,错误原因:.
        /// </summary>
        internal static string frmOther_cmdUpdateNews_Click_核查网站新闻失败_错误原因_ {
            get {
                return ResourceManager.GetString("frmOther_cmdUpdateNews_Click_核查网站新闻失败_错误原因_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 核查网站新闻成功!.
        /// </summary>
        internal static string frmOther_cmdUpdateNews_Click_核查网站新闻成功_ {
            get {
                return ResourceManager.GetString("frmOther_cmdUpdateNews_Click_核查网站新闻成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除该询问信息失败,错误原因:
        ///!.
        /// </summary>
        internal static string frmQnA_cmdDelete_Click_ {
            get {
                return ResourceManager.GetString("frmQnA_cmdDelete_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除该询问信息成功!.
        /// </summary>
        internal static string frmQnA_cmdDelete_Click_删除该询问信息成功_ {
            get {
                return ResourceManager.GetString("frmQnA_cmdDelete_Click_删除该询问信息成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询客户询问数据错误!.
        /// </summary>
        internal static string frmQnA_RefreshSecondHands_查询客户询问数据错误_ {
            get {
                return ResourceManager.GetString("frmQnA_RefreshSecondHands_查询客户询问数据错误_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 咨询回复失败!请重新递交,错误原因:
        ///.
        /// </summary>
        internal static string frmQnA_S_Click_ {
            get {
                return ResourceManager.GetString("frmQnA_S_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 咨询回复成功!.
        /// </summary>
        internal static string frmQnA_S_Click_咨询回复成功_ {
            get {
                return ResourceManager.GetString("frmQnA_S_Click_咨询回复成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除该二手信息失败,错误原因:
        ///!.
        /// </summary>
        internal static string frmSecondHands_cmdDelete_Click_ {
            get {
                return ResourceManager.GetString("frmSecondHands_cmdDelete_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除该二手信息成功!.
        /// </summary>
        internal static string frmSecondHands_cmdDelete_Click_删除该二手信息成功_ {
            get {
                return ResourceManager.GetString("frmSecondHands_cmdDelete_Click_删除该二手信息成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询二手机型数据错误!.
        /// </summary>
        internal static string frmSecondHands_RefreshSecondHands_查询二手机型数据错误_ {
            get {
                return ResourceManager.GetString("frmSecondHands_RefreshSecondHands_查询二手机型数据错误_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改价格失败!请重新递交,错误原因:
        ///.
        /// </summary>
        internal static string frmSecondHands_S_Click_ {
            get {
                return ResourceManager.GetString("frmSecondHands_S_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改价格成功!.
        /// </summary>
        internal static string frmSecondHands_S_Click_修改价格成功_ {
            get {
                return ResourceManager.GetString("frmSecondHands_S_Click_修改价格成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他1.
        /// </summary>
        internal static string frmViewPicture_ChangeText_其他1 {
            get {
                return ResourceManager.GetString("frmViewPicture_ChangeText_其他1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他2.
        /// </summary>
        internal static string frmViewPicture_ChangeText_其他2 {
            get {
                return ResourceManager.GetString("frmViewPicture_ChangeText_其他2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他3.
        /// </summary>
        internal static string frmViewPicture_ChangeText_其他3 {
            get {
                return ResourceManager.GetString("frmViewPicture_ChangeText_其他3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正面图.
        /// </summary>
        internal static string frmViewPicture_ChangeText_正面图 {
            get {
                return ResourceManager.GetString("frmViewPicture_ChangeText_正面图", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背面图.
        /// </summary>
        internal static string frmViewPicture_ChangeText_背面图 {
            get {
                return ResourceManager.GetString("frmViewPicture_ChangeText_背面图", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Loging {
            get {
                object obj = ResourceManager.GetObject("Loging", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误的参数! 请从CRM管理系统或CMS系统中启动本程序!.
        /// </summary>
        internal static string Program_Main_错误的参数__请从CRM管理系统或CMS系统中启动本程序_ {
            get {
                return ResourceManager.GetString("Program_Main_错误的参数__请从CRM管理系统或CMS系统中启动本程序_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap windows7_innerlight_by_remixedcat {
            get {
                object obj = ResourceManager.GetObject("windows7-innerlight-by-remixedcat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
