//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileShopERP.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileShopERP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1290168401_button_ok {
            get {
                object obj = ResourceManager.GetObject("1290168401_button_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1295664696_Credit_Card {
            get {
                object obj = ResourceManager.GetObject("1295664696_Credit_Card", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1303232260_system_software_update {
            get {
                object obj = ResourceManager.GetObject("1303232260_system-software-update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2006106225525122 {
            get {
                object obj = ResourceManager.GetObject("2006106225525122", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _22 {
            get {
                object obj = ResourceManager.GetObject("22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap About {
            get {
                object obj = ResourceManager.GetObject("About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addressbook_add128 {
            get {
                object obj = ResourceManager.GetObject("addressbook-add128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addressbook_edit128 {
            get {
                object obj = ResourceManager.GetObject("addressbook-edit128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap addressbook_search128 {
            get {
                object obj = ResourceManager.GetObject("addressbook-search128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ajax_loader {
            get {
                object obj = ResourceManager.GetObject("ajax-loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap binary_tree128 {
            get {
                object obj = ResourceManager.GetObject("binary-tree128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap catalog128 {
            get {
                object obj = ResourceManager.GetObject("catalog128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap distributor_report128 {
            get {
                object obj = ResourceManager.GetObject("distributor-report128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frmAddPhone {
            get {
                object obj = ResourceManager.GetObject("frmAddPhone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string frmAddPhone_ckbEquip_CheckedChanged__0 {
            get {
                return ResourceManager.GetString("frmAddPhone_ckbEquip_CheckedChanged__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的保修卡销售价格! 的本地化字符串。
        /// </summary>
        internal static string frmAddPhone_cmdOK_Click_请填写正确的保修卡销售价格_ {
            get {
                return ResourceManager.GetString("frmAddPhone_cmdOK_Click_请填写正确的保修卡销售价格_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的手机IMEI! 的本地化字符串。
        /// </summary>
        internal static string frmAddPhone_cmdOK_Click_请填写正确的手机IMEI_ {
            get {
                return ResourceManager.GetString("frmAddPhone_cmdOK_Click_请填写正确的手机IMEI_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的手机成本价格! 的本地化字符串。
        /// </summary>
        internal static string frmAddPhone_cmdOK_Click_请填写正确的手机成本价格_ {
            get {
                return ResourceManager.GetString("frmAddPhone_cmdOK_Click_请填写正确的手机成本价格_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的手机销售价格! 的本地化字符串。
        /// </summary>
        internal static string frmAddPhone_cmdOK_Click_请填写正确的手机销售价格_ {
            get {
                return ResourceManager.GetString("frmAddPhone_cmdOK_Click_请填写正确的手机销售价格_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的配件成本价格! 的本地化字符串。
        /// </summary>
        internal static string frmAddPhone_cmdOK_Click_请填写正确的配件成本价格_ {
            get {
                return ResourceManager.GetString("frmAddPhone_cmdOK_Click_请填写正确的配件成本价格_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的配件销售价格! 的本地化字符串。
        /// </summary>
        internal static string frmAddPhone_cmdOK_Click_请填写正确的配件销售价格_ {
            get {
                return ResourceManager.GetString("frmAddPhone_cmdOK_Click_请填写正确的配件销售价格_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择正确的手机型号! 的本地化字符串。
        /// </summary>
        internal static string frmAddPhone_cmdOK_Click_请选择正确的手机型号_ {
            get {
                return ResourceManager.GetString("frmAddPhone_cmdOK_Click_请选择正确的手机型号_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择正确的生产厂商! 的本地化字符串。
        /// </summary>
        internal static string frmAddPhone_cmdOK_Click_请选择正确的生产厂商_ {
            get {
                return ResourceManager.GetString("frmAddPhone_cmdOK_Click_请选择正确的生产厂商_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择正确的销售人员! 的本地化字符串。
        /// </summary>
        internal static string frmAddPhone_cmdOK_Click_请选择正确的销售人员_ {
            get {
                return ResourceManager.GetString("frmAddPhone_cmdOK_Click_请选择正确的销售人员_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string frmAddPhone_frmAddPhone_Load_修改 {
            get {
                return ResourceManager.GetString("frmAddPhone_frmAddPhone_Load_修改", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加 的本地化字符串。
        /// </summary>
        internal static string frmAddPhone_frmAddPhone_Load_增加 {
            get {
                return ResourceManager.GetString("frmAddPhone_frmAddPhone_Load_增加", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库连接失败! 的本地化字符串。
        /// </summary>
        internal static string frmAddPhone_frmAddPhone_Load_数据库连接失败_ {
            get {
                return ResourceManager.GetString("frmAddPhone_frmAddPhone_Load_数据库连接失败_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加请假记录失败! 错误原因:
        /// 的本地化字符串。
        /// </summary>
        internal static string frmAskforLeave_cmdAdd_Click_ {
            get {
                return ResourceManager.GetString("frmAskforLeave_cmdAdd_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加请假记录成功! 的本地化字符串。
        /// </summary>
        internal static string frmAskforLeave_cmdAdd_Click_添加请假记录成功_ {
            get {
                return ResourceManager.GetString("frmAskforLeave_cmdAdd_Click_添加请假记录成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除记录失败! 错误原因:
        /// 的本地化字符串。
        /// </summary>
        internal static string frmAskforLeave_cmdDelete_Click_ {
            get {
                return ResourceManager.GetString("frmAskforLeave_cmdDelete_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除记录成功! 的本地化字符串。
        /// </summary>
        internal static string frmAskforLeave_cmdDelete_Click_删除记录成功_ {
            get {
                return ResourceManager.GetString("frmAskforLeave_cmdDelete_Click_删除记录成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须选择一个销售人员进行查看! 的本地化字符串。
        /// </summary>
        internal static string frmAskforLeave_cmdSearch_Click_必须选择一个销售人员进行查看_ {
            get {
                return ResourceManager.GetString("frmAskforLeave_cmdSearch_Click_必须选择一个销售人员进行查看_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询不到任何记录! 的本地化字符串。
        /// </summary>
        internal static string frmAskforLeave_cmdSearch_Click_查询不到任何记录_ {
            get {
                return ResourceManager.GetString("frmAskforLeave_cmdSearch_Click_查询不到任何记录_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的请假时间! 的本地化字符串。
        /// </summary>
        internal static string frmAskforLeaveEditor_cmdOK_Click_请填写正确的请假时间_ {
            get {
                return ResourceManager.GetString("frmAskforLeaveEditor_cmdOK_Click_请填写正确的请假时间_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改请假记录 -- 销售人员:  的本地化字符串。
        /// </summary>
        internal static string frmAskforLeaveEditor_frmAskforLeaveEditor_Load_修改请假记录____销售人员__ {
            get {
                return ResourceManager.GetString("frmAskforLeaveEditor_frmAskforLeaveEditor_Load_修改请假记录____销售人员__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string frmBinPhone_ckbisSold_CheckedChanged__0 {
            get {
                return ResourceManager.GetString("frmBinPhone_ckbisSold_CheckedChanged__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已出售 的本地化字符串。
        /// </summary>
        internal static string frmBinPhone_ckbisSold_CheckedChanged_已出售 {
            get {
                return ResourceManager.GetString("frmBinPhone_ckbisSold_CheckedChanged_已出售", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未出售 的本地化字符串。
        /// </summary>
        internal static string frmBinPhone_ckbisSold_CheckedChanged_未出售 {
            get {
                return ResourceManager.GetString("frmBinPhone_ckbisSold_CheckedChanged_未出售", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加二手机回收失败,失败原因: 的本地化字符串。
        /// </summary>
        internal static string frmBinPhone_cmdAdd_Click_添加二手机回收失败_失败原因_ {
            get {
                return ResourceManager.GetString("frmBinPhone_cmdAdd_Click_添加二手机回收失败_失败原因_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加二手机回收完成,已成功添加: 的本地化字符串。
        /// </summary>
        internal static string frmBinPhone_cmdAdd_Click_添加二手机回收完成_已成功添加_ {
            get {
                return ResourceManager.GetString("frmBinPhone_cmdAdd_Click_添加二手机回收完成_已成功添加_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的手机IMEI! 的本地化字符串。
        /// </summary>
        internal static string frmBinPhone_cmdAdd_Click_请填写正确的手机IMEI_ {
            get {
                return ResourceManager.GetString("frmBinPhone_cmdAdd_Click_请填写正确的手机IMEI_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的手机名称! 的本地化字符串。
        /// </summary>
        internal static string frmBinPhone_cmdAdd_Click_请填写正确的手机名称_ {
            get {
                return ResourceManager.GetString("frmBinPhone_cmdAdd_Click_请填写正确的手机名称_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的手机收取价格! 的本地化字符串。
        /// </summary>
        internal static string frmBinPhone_cmdAdd_Click_请填写正确的手机收取价格_ {
            get {
                return ResourceManager.GetString("frmBinPhone_cmdAdd_Click_请填写正确的手机收取价格_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的手机维修价格! 的本地化字符串。
        /// </summary>
        internal static string frmBinPhone_cmdAdd_Click_请填写正确的手机维修价格_ {
            get {
                return ResourceManager.GetString("frmBinPhone_cmdAdd_Click_请填写正确的手机维修价格_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除二手机回收失败,失败原因: 的本地化字符串。
        /// </summary>
        internal static string frmBinPhone_cmdDelete_Click_删除二手机回收失败_失败原因_ {
            get {
                return ResourceManager.GetString("frmBinPhone_cmdDelete_Click_删除二手机回收失败_失败原因_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除二手机回收完成 的本地化字符串。
        /// </summary>
        internal static string frmBinPhone_cmdDelete_Click_删除二手机回收完成_已成功添加_ {
            get {
                return ResourceManager.GetString("frmBinPhone_cmdDelete_Click_删除二手机回收完成_已成功添加_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改二手机回收失败,失败原因: 的本地化字符串。
        /// </summary>
        internal static string frmBinPhone_cmdUpdate_Click_修改二手机回收失败_失败原因_ {
            get {
                return ResourceManager.GetString("frmBinPhone_cmdUpdate_Click_修改二手机回收失败_失败原因_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改二手机回收完成,已成功更改: 的本地化字符串。
        /// </summary>
        internal static string frmBinPhone_cmdUpdate_Click_修改二手机回收完成_已成功更改_ {
            get {
                return ResourceManager.GetString("frmBinPhone_cmdUpdate_Click_修改二手机回收完成_已成功更改_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap frmBinPhonesEditor {
            get {
                object obj = ResourceManager.GetObject("frmBinPhonesEditor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string frmCommision_cmdView_Click__0 {
            get {
                return ResourceManager.GetString("frmCommision_cmdView_Click__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须选择一个销售人员再进行查看! 的本地化字符串。
        /// </summary>
        internal static string frmCommision_cmdView_Click_必须选择一个销售人员再进行查看_ {
            get {
                return ResourceManager.GetString("frmCommision_cmdView_Click_必须选择一个销售人员再进行查看_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询提成失败! 的本地化字符串。
        /// </summary>
        internal static string frmCommision_cmdView_Click_查询提成失败_ {
            get {
                return ResourceManager.GetString("frmCommision_cmdView_Click_查询提成失败_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非销售人员或店员没有提成! 的本地化字符串。
        /// </summary>
        internal static string frmCommision_cmdView_Click_非销售人员或店员没有提成_ {
            get {
                return ResourceManager.GetString("frmCommision_cmdView_Click_非销售人员或店员没有提成_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string frmCustomDebt_CleanUI__0 {
            get {
                return ResourceManager.GetString("frmCustomDebt_CleanUI__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加客户欠款失败,失败原因: 的本地化字符串。
        /// </summary>
        internal static string frmCustomDebt_cmdAdd_Click_添加客户欠款失败_失败原因_ {
            get {
                return ResourceManager.GetString("frmCustomDebt_cmdAdd_Click_添加客户欠款失败_失败原因_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加客户欠款成功! 的本地化字符串。
        /// </summary>
        internal static string frmCustomDebt_cmdAdd_Click_添加客户欠款成功_ {
            get {
                return ResourceManager.GetString("frmCustomDebt_cmdAdd_Click_添加客户欠款成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的客户欠款事项! 的本地化字符串。
        /// </summary>
        internal static string frmCustomDebt_cmdAdd_Click_请填写正确的客户欠款事项_ {
            get {
                return ResourceManager.GetString("frmCustomDebt_cmdAdd_Click_请填写正确的客户欠款事项_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的客户欠款人名称! 的本地化字符串。
        /// </summary>
        internal static string frmCustomDebt_cmdAdd_Click_请填写正确的客户欠款人名称_ {
            get {
                return ResourceManager.GetString("frmCustomDebt_cmdAdd_Click_请填写正确的客户欠款人名称_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的客户欠款金额! 的本地化字符串。
        /// </summary>
        internal static string frmCustomDebt_cmdAdd_Click_请填写正确的客户欠款金额_ {
            get {
                return ResourceManager.GetString("frmCustomDebt_cmdAdd_Click_请填写正确的客户欠款金额_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除指定欠款失败! 错误原因: 的本地化字符串。
        /// </summary>
        internal static string frmCustomDebt_cmdDelete_Click_删除指定欠款失败__错误原因_ {
            get {
                return ResourceManager.GetString("frmCustomDebt_cmdDelete_Click_删除指定欠款失败__错误原因_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除指定欠款成功! 的本地化字符串。
        /// </summary>
        internal static string frmCustomDebt_cmdDelete_Click_删除指定欠款成功_ {
            get {
                return ResourceManager.GetString("frmCustomDebt_cmdDelete_Click_删除指定欠款成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改指定欠款到帐失败! 的本地化字符串。
        /// </summary>
        internal static string frmCustomDebt_cmdFinish_Click_修改指定欠款到帐失败_ {
            get {
                return ResourceManager.GetString("frmCustomDebt_cmdFinish_Click_修改指定欠款到帐失败_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改指定欠款到帐成功! 的本地化字符串。
        /// </summary>
        internal static string frmCustomDebt_cmdFinish_Click_修改指定欠款到帐成功_ {
            get {
                return ResourceManager.GetString("frmCustomDebt_cmdFinish_Click_修改指定欠款到帐成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未查询到任何数据! 的本地化字符串。
        /// </summary>
        internal static string frmDailySell_cmdViewDaily_Click_未查询到任何数据_ {
            get {
                return ResourceManager.GetString("frmDailySell_cmdViewDaily_Click_未查询到任何数据_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 永久删除用户失败! 错误原因: 的本地化字符串。
        /// </summary>
        internal static string frmEditCustem_cmdDeleteCustom_Click_永久删除用户失败__错误原因_ {
            get {
                return ResourceManager.GetString("frmEditCustem_cmdDeleteCustom_Click_永久删除用户失败__错误原因_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 永久删除用户成功! 的本地化字符串。
        /// </summary>
        internal static string frmEditCustem_cmdDeleteCustom_Click_永久删除用户成功_ {
            get {
                return ResourceManager.GetString("frmEditCustem_cmdDeleteCustom_Click_永久删除用户成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 永久删除该手机失败! 失败原因: 的本地化字符串。
        /// </summary>
        internal static string frmEditCustem_cmdDeletePhone_Click_永久删除该手机失败__失败原因_ {
            get {
                return ResourceManager.GetString("frmEditCustem_cmdDeletePhone_Click_永久删除该手机失败__失败原因_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 永久删除该手机成功! 的本地化字符串。
        /// </summary>
        internal static string frmEditCustem_cmdDeletePhone_Click_永久删除该手机成功_ {
            get {
                return ResourceManager.GetString("frmEditCustem_cmdDeletePhone_Click_永久删除该手机成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询客户数据失败,失败原因:
        /// 的本地化字符串。
        /// </summary>
        internal static string frmEditCustem_cmdSearch_Click_ {
            get {
                return ResourceManager.GetString("frmEditCustem_cmdSearch_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须填写手机号,手机串号或保修卡任意一项! 的本地化字符串。
        /// </summary>
        internal static string frmEditCustem_cmdSearch_Click_必须填写手机号_手机串号或保修卡任意一项_ {
            get {
                return ResourceManager.GetString("frmEditCustem_cmdSearch_Click_必须填写手机号_手机串号或保修卡任意一项_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未搜索到任何用户资料! 的本地化字符串。
        /// </summary>
        internal static string frmEditCustem_cmdSearch_Click_未搜索到任何用户资料_ {
            get {
                return ResourceManager.GetString("frmEditCustem_cmdSearch_Click_未搜索到任何用户资料_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改用户失败!错误原因
        /// 的本地化字符串。
        /// </summary>
        internal static string frmEditCustem_cmdUpdate_Click_ {
            get {
                return ResourceManager.GetString("frmEditCustem_cmdUpdate_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改用户成功! 的本地化字符串。
        /// </summary>
        internal static string frmEditCustem_cmdUpdate_Click_修改用户成功_ {
            get {
                return ResourceManager.GetString("frmEditCustem_cmdUpdate_Click_修改用户成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经勾选保修卡,但未填写保修卡编号! 的本地化字符串。
        /// </summary>
        internal static string frmEditCustem_cmdUpdate_Click_已经勾选保修卡_但未填写保修卡编号_ {
            get {
                return ResourceManager.GetString("frmEditCustem_cmdUpdate_Click_已经勾选保修卡_但未填写保修卡编号_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有 的本地化字符串。
        /// </summary>
        internal static string frmEditCustem_cmdUpdate_Click_有 {
            get {
                return ResourceManager.GetString("frmEditCustem_cmdUpdate_Click_有", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的手机号码! 的本地化字符串。
        /// </summary>
        internal static string frmEditCustem_cmdUpdate_Click_请填写正确的手机号码_ {
            get {
                return ResourceManager.GetString("frmEditCustem_cmdUpdate_Click_请填写正确的手机号码_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国行 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmbBuyer_SelectedIndexChanged_国行 {
            get {
                return ResourceManager.GetString("frmEditPhone_cmbBuyer_SelectedIndexChanged_国行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水货 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmbBuyer_SelectedIndexChanged_水货 {
            get {
                return ResourceManager.GetString("frmEditPhone_cmbBuyer_SelectedIndexChanged_水货", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 港行 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmbBuyer_SelectedIndexChanged_港行 {
            get {
                return ResourceManager.GetString("frmEditPhone_cmbBuyer_SelectedIndexChanged_港行", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除该部手机失败! 错误原因: 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdDeltePhone_Click_删除该部手机失败__错误原因_ {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdDeltePhone_Click_删除该部手机失败__错误原因_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除该部手机成功! 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdDeltePhone_Click_删除该部手机成功_ {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdDeltePhone_Click_删除该部手机成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一年 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdSearch_Click_一年 {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdSearch_Click_一年", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三年 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdSearch_Click_三年 {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdSearch_Click_三年", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两年 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdSearch_Click_两年 {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdSearch_Click_两年", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdSearch_Click_年 {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdSearch_Click_年", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 延长保修 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdSearch_Click_延长保修 {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdSearch_Click_延长保修", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无敌保修 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdSearch_Click_无敌保修 {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdSearch_Click_无敌保修", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdSearch_Click_日 {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdSearch_Click_日", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdSearch_Click_月 {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdSearch_Click_月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有在数据库里找到串号为 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdSearch_Click_没有在数据库里找到串号为 {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdSearch_Click_没有在数据库里找到串号为", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 的手机 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdSearch_Click_的手机 {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdSearch_Click_的手机", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终身 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdSearch_Click_终身 {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdSearch_Click_终身", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该手机已退货 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdSearch_Click_该手机已退货 {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdSearch_Click_该手机已退货", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的串号再进行查询! 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdSearch_Click_请填写正确的串号再进行查询_ {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdSearch_Click_请填写正确的串号再进行查询_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件保修 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdSearch_Click_软件保修 {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdSearch_Click_软件保修", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软硬全保 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdSearch_Click_软硬全保 {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdSearch_Click_软硬全保", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改手机保修失败!错误原因:
        /// 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdUpdate_Click_ {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdUpdate_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改手机保修成功! 的本地化字符串。
        /// </summary>
        internal static string frmEditPhone_cmdUpdate_Click_修改手机保修成功_ {
            get {
                return ResourceManager.GetString("frmEditPhone_cmdUpdate_Click_修改手机保修成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string frmEquipSell_CleanUI__0 {
            get {
                return ResourceManager.GetString("frmEquipSell_CleanUI__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加配件销售记录失败,错误原因: 的本地化字符串。
        /// </summary>
        internal static string frmEquipSell_cmdAdd_Click_添加配件销售记录失败_错误原因_ {
            get {
                return ResourceManager.GetString("frmEquipSell_cmdAdd_Click_添加配件销售记录失败_错误原因_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加配件销售记录成功,已经成功添加 的本地化字符串。
        /// </summary>
        internal static string frmEquipSell_cmdAdd_Click_添加配件销售记录成功_已经成功添加 {
            get {
                return ResourceManager.GetString("frmEquipSell_cmdAdd_Click_添加配件销售记录成功_已经成功添加", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的配件名称! 的本地化字符串。
        /// </summary>
        internal static string frmEquipSell_cmdAdd_Click_请填写正确的配件名称_ {
            get {
                return ResourceManager.GetString("frmEquipSell_cmdAdd_Click_请填写正确的配件名称_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的配件成本价格! 的本地化字符串。
        /// </summary>
        internal static string frmEquipSell_cmdAdd_Click_请填写正确的配件成本价格_ {
            get {
                return ResourceManager.GetString("frmEquipSell_cmdAdd_Click_请填写正确的配件成本价格_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的配件销售价格! 的本地化字符串。
        /// </summary>
        internal static string frmEquipSell_cmdAdd_Click_请填写正确的配件销售价格_ {
            get {
                return ResourceManager.GetString("frmEquipSell_cmdAdd_Click_请填写正确的配件销售价格_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除指定配件销售记录失败! 错误原因: 的本地化字符串。
        /// </summary>
        internal static string frmEquipSell_cmdDelete_Click_删除指定配件销售记录失败__错误原因_ {
            get {
                return ResourceManager.GetString("frmEquipSell_cmdDelete_Click_删除指定配件销售记录失败__错误原因_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除指定配件销售记录成功! 的本地化字符串。
        /// </summary>
        internal static string frmEquipSell_cmdDelete_Click_删除指定配件销售记录成功_ {
            get {
                return ResourceManager.GetString("frmEquipSell_cmdDelete_Click_删除指定配件销售记录成功_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap frmEquipSellEditor {
            get {
                object obj = ResourceManager.GetObject("frmEquipSellEditor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似  Version: 的本地化字符串。
        /// </summary>
        internal static string frmLogin_frmLogin_Load__Version_ {
            get {
                return ResourceManager.GetString("frmLogin_frmLogin_Load__Version_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今日固定支出 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_今日支出收益 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_今日支出收益", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改客户 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_修改客户 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_修改客户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷卡识别 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_刷卡识别 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_刷卡识别", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户欠款管理 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_客户欠款管理 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_客户欠款管理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 市场欠款 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_市场欠款 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_市场欠款", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 市场结帐 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_市场结帐 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_市场结帐", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量查询客户 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_批量查询客户 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_批量查询客户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看今日配件销售 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_查看今日配件销售 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_查看今日配件销售", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看今日销售 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_查看今日销售 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_查看今日销售", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看利润 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_查看利润 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_查看利润", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看固定支出 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_查看支出收益 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_查看支出收益", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看销售人员请假记录 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_查看销售人员请假记录 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_查看销售人员请假记录", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询手机 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_查询手机 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_查询手机", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测数据库 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_检测数据库 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_检测数据库", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测网络 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_检测网络 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_检测网络", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加客户 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_添加客户 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_添加客户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_系统设置 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_系统设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收二手机 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_返收客户手机 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_返收客户手机", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卖二手机 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_返收手机销售 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_返收手机销售", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配件销售 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_配件销售 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_配件销售", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售人员 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_销售人员 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_销售人员", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售人员提成 的本地化字符串。
        /// </summary>
        internal static string frmMain_ShowInfo_销售人员提成 {
            get {
                return ResourceManager.GetString("frmMain_ShowInfo_销售人员提成", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 龙翔数据库连接失败! 的本地化字符串。
        /// </summary>
        internal static string frmMain_数据库ToolStripMenuItem_Click_龙翔数据库连接失败_ {
            get {
                return ResourceManager.GetString("frmMain_数据库ToolStripMenuItem_Click_龙翔数据库连接失败_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 龙翔数据库连接正常! 的本地化字符串。
        /// </summary>
        internal static string frmMain_数据库ToolStripMenuItem_Click_龙翔数据库连接正常_ {
            get {
                return ResourceManager.GetString("frmMain_数据库ToolStripMenuItem_Click_龙翔数据库连接正常_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 龙翔服务器网络连接失败! 的本地化字符串。
        /// </summary>
        internal static string frmMain_网站FTPToolStripMenuItem_Click_龙翔服务器网络连接失败_ {
            get {
                return ResourceManager.GetString("frmMain_网站FTPToolStripMenuItem_Click_龙翔服务器网络连接失败_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 龙翔服务器网络连接正常! 的本地化字符串。
        /// </summary>
        internal static string frmMain_网站FTPToolStripMenuItem_Click_龙翔服务器网络连接正常_ {
            get {
                return ResourceManager.GetString("frmMain_网站FTPToolStripMenuItem_Click_龙翔服务器网络连接正常_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string frmMarketDebt_CleanUI__0 {
            get {
                return ResourceManager.GetString("frmMarketDebt_CleanUI__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加市场欠款失败! 错误原因: 的本地化字符串。
        /// </summary>
        internal static string frmMarketDebt_cmdAdd_Click_添加市场欠款失败__错误原因_ {
            get {
                return ResourceManager.GetString("frmMarketDebt_cmdAdd_Click_添加市场欠款失败__错误原因_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加市场欠款成功! 的本地化字符串。
        /// </summary>
        internal static string frmMarketDebt_cmdAdd_Click_添加市场欠款成功_ {
            get {
                return ResourceManager.GetString("frmMarketDebt_cmdAdd_Click_添加市场欠款成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的市场欠款事项! 的本地化字符串。
        /// </summary>
        internal static string frmMarketDebt_cmdAdd_Click_请填写正确的市场欠款事项_ {
            get {
                return ResourceManager.GetString("frmMarketDebt_cmdAdd_Click_请填写正确的市场欠款事项_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的市场欠款债权人! 的本地化字符串。
        /// </summary>
        internal static string frmMarketDebt_cmdAdd_Click_请填写正确的市场欠款债权人_ {
            get {
                return ResourceManager.GetString("frmMarketDebt_cmdAdd_Click_请填写正确的市场欠款债权人_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的市场欠款金额! 的本地化字符串。
        /// </summary>
        internal static string frmMarketDebt_cmdAdd_Click_请填写正确的市场欠款金额_ {
            get {
                return ResourceManager.GetString("frmMarketDebt_cmdAdd_Click_请填写正确的市场欠款金额_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除指定的市场欠款失败!失败原因: 的本地化字符串。
        /// </summary>
        internal static string frmMarketDebt_cmdDelete_Click_删除指定的市场欠款失败_失败原因_ {
            get {
                return ResourceManager.GetString("frmMarketDebt_cmdDelete_Click_删除指定的市场欠款失败_失败原因_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除指定的市场欠款成功 的本地化字符串。
        /// </summary>
        internal static string frmMarketDebt_cmdDelete_Click_删除指定的市场欠款成功 {
            get {
                return ResourceManager.GetString("frmMarketDebt_cmdDelete_Click_删除指定的市场欠款成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的市场结款失败!失败原因: 的本地化字符串。
        /// </summary>
        internal static string frmMarketDebt_cmdFix_Click_指定的市场结款失败_失败原因_ {
            get {
                return ResourceManager.GetString("frmMarketDebt_cmdFix_Click_指定的市场结款失败_失败原因_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的市场结款成功! 的本地化字符串。
        /// </summary>
        internal static string frmMarketDebt_cmdFix_Click_指定的市场结款成功_ {
            get {
                return ResourceManager.GetString("frmMarketDebt_cmdFix_Click_指定的市场结款成功_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap frmMarketDebtEditor {
            get {
                object obj = ResourceManager.GetObject("frmMarketDebtEditor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 0.0 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_ckbEquip_CheckedChanged__0 {
            get {
                return ResourceManager.GetString("frmNewCustom_ckbEquip_CheckedChanged__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N/A 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_CleanUI_N_A {
            get {
                return ResourceManager.GetString("frmNewCustom_CleanUI_N_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0.0 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_cmbPayment_SelectedIndexChanged__0 {
            get {
                return ResourceManager.GetString("frmNewCustom_cmbPayment_SelectedIndexChanged__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加用户失败!错误原因:
        /// 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_cmdAddUser_Click_ {
            get {
                return ResourceManager.GetString("frmNewCustom_cmdAddUser_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , 购买机型为 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_cmdAddUser_Click___购买机型为 {
            get {
                return ResourceManager.GetString("frmNewCustom_cmdAddUser_Click___购买机型为", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刚刚添加的用户为: 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_cmdAddUser_Click_刚刚添加的用户为_ {
            get {
                return ResourceManager.GetString("frmNewCustom_cmdAddUser_Click_刚刚添加的用户为_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经勾选保修卡,但未填写保修卡编号! 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_cmdAddUser_Click_已经勾选保修卡_但未填写保修卡编号_ {
            get {
                return ResourceManager.GetString("frmNewCustom_cmdAddUser_Click_已经勾选保修卡_但未填写保修卡编号_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经存在该用户,将跳转到用户修改页面进行操作! 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_cmdAddUser_Click_已经存在该用户_将跳转到用户修改页面进行操作_ {
            get {
                return ResourceManager.GetString("frmNewCustom_cmdAddUser_Click_已经存在该用户_将跳转到用户修改页面进行操作_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加用户成功,已经添加用户: 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_cmdAddUser_Click_添加用户成功_已经添加用户_ {
            get {
                return ResourceManager.GetString("frmNewCustom_cmdAddUser_Click_添加用户成功_已经添加用户_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的保修卡销售价格! 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_cmdAddUser_Click_请填写正确的保修卡销售价格_ {
            get {
                return ResourceManager.GetString("frmNewCustom_cmdAddUser_Click_请填写正确的保修卡销售价格_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的已支付款额! 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_cmdAddUser_Click_请填写正确的已支付款额_ {
            get {
                return ResourceManager.GetString("frmNewCustom_cmdAddUser_Click_请填写正确的已支付款额_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的手机IMEI! 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_cmdAddUser_Click_请填写正确的手机IMEI_ {
            get {
                return ResourceManager.GetString("frmNewCustom_cmdAddUser_Click_请填写正确的手机IMEI_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的手机号码! 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_cmdAddUser_Click_请填写正确的手机号码_ {
            get {
                return ResourceManager.GetString("frmNewCustom_cmdAddUser_Click_请填写正确的手机号码_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的手机成本价格! 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_cmdAddUser_Click_请填写正确的手机成本价格_ {
            get {
                return ResourceManager.GetString("frmNewCustom_cmdAddUser_Click_请填写正确的手机成本价格_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的手机销售价格! 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_cmdAddUser_Click_请填写正确的手机销售价格_ {
            get {
                return ResourceManager.GetString("frmNewCustom_cmdAddUser_Click_请填写正确的手机销售价格_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的配件成本价格! 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_cmdAddUser_Click_请填写正确的配件成本价格_ {
            get {
                return ResourceManager.GetString("frmNewCustom_cmdAddUser_Click_请填写正确的配件成本价格_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写正确的配件销售价格! 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_cmdAddUser_Click_请填写正确的配件销售价格_ {
            get {
                return ResourceManager.GetString("frmNewCustom_cmdAddUser_Click_请填写正确的配件销售价格_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择正确的手机型号! 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_cmdAddUser_Click_请选择正确的手机型号_ {
            get {
                return ResourceManager.GetString("frmNewCustom_cmdAddUser_Click_请选择正确的手机型号_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择正确的生产厂商! 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_cmdAddUser_Click_请选择正确的生产厂商_ {
            get {
                return ResourceManager.GetString("frmNewCustom_cmdAddUser_Click_请选择正确的生产厂商_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择正确的销售人员! 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_cmdAddUser_Click_请选择正确的销售人员_ {
            get {
                return ResourceManager.GetString("frmNewCustom_cmdAddUser_Click_请选择正确的销售人员_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库连接失败! 的本地化字符串。
        /// </summary>
        internal static string frmNewCustom_frmNewCustom_Load_数据库连接失败_ {
            get {
                return ResourceManager.GetString("frmNewCustom_frmNewCustom_Load_数据库连接失败_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string frmPayout_CleanUI__0 {
            get {
                return ResourceManager.GetString("frmPayout_CleanUI__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加记录失败!错误原因:
        /// 的本地化字符串。
        /// </summary>
        internal static string frmPayout_cmdAdd_Click_ {
            get {
                return ResourceManager.GetString("frmPayout_cmdAdd_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加支出记录成功 的本地化字符串。
        /// </summary>
        internal static string frmPayout_cmdAdd_Click_添加支出记录成功 {
            get {
                return ResourceManager.GetString("frmPayout_cmdAdd_Click_添加支出记录成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请正确填写金额! 的本地化字符串。
        /// </summary>
        internal static string frmPayout_cmdAdd_Click_请正确填写金额_ {
            get {
                return ResourceManager.GetString("frmPayout_cmdAdd_Click_请正确填写金额_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除支出记录失败
        /// 的本地化字符串。
        /// </summary>
        internal static string frmPayout_cmdDelete_Click_ {
            get {
                return ResourceManager.GetString("frmPayout_cmdDelete_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除支出记录成功! 的本地化字符串。
        /// </summary>
        internal static string frmPayout_cmdDelete_Click_删除支出记录成功_ {
            get {
                return ResourceManager.GetString("frmPayout_cmdDelete_Click_删除支出记录成功_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap frmPayoutEditor {
            get {
                object obj = ResourceManager.GetObject("frmPayoutEditor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string frmPrivatePay_CleanUI__0 {
            get {
                return ResourceManager.GetString("frmPrivatePay_CleanUI__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请正确填写金额! 的本地化字符串。
        /// </summary>
        internal static string frmPrivatePay_cmdAdd_Click_请正确填写金额_ {
            get {
                return ResourceManager.GetString("frmPrivatePay_cmdAdd_Click_请正确填写金额_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 的本地化字符串。
        /// </summary>
        internal static string frmProfit_frmProfit_Load__0 {
            get {
                return ResourceManager.GetString("frmProfit_frmProfit_Load__0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载厂商列表失败! 的本地化字符串。
        /// </summary>
        internal static string frmProfit_frmProfit_Load_下载厂商列表失败_ {
            get {
                return ResourceManager.GetString("frmProfit_frmProfit_Load_下载厂商列表失败_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取利润及提成错误! 的本地化字符串。
        /// </summary>
        internal static string frmProfit_frmProfit_Load_读取利润及提成错误_ {
            get {
                return ResourceManager.GetString("frmProfit_frmProfit_Load_读取利润及提成错误_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取固定支出错误! 的本地化字符串。
        /// </summary>
        internal static string frmProfit_frmProfit_Load_读取固定支出错误_ {
            get {
                return ResourceManager.GetString("frmProfit_frmProfit_Load_读取固定支出错误_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择一个用于输出的文件夹 的本地化字符串。
        /// </summary>
        internal static string frmReport_cmdDailyPath_Click_选择一个用于输出的文件夹 {
            get {
                return ResourceManager.GetString("frmReport_cmdDailyPath_Click_选择一个用于输出的文件夹", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户更改失败
        /// 的本地化字符串。
        /// </summary>
        internal static string frmSellers_button1_Click_ {
            get {
                return ResourceManager.GetString("frmSellers_button1_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户更改已经成功 的本地化字符串。
        /// </summary>
        internal static string frmSellers_button1_Click_用户更改已经成功 {
            get {
                return ResourceManager.GetString("frmSellers_button1_Click_用户更改已经成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员姓名 的本地化字符串。
        /// </summary>
        internal static string frmSellers_frmSellers_Load_人员姓名 {
            get {
                return ResourceManager.GetString("frmSellers_frmSellers_Load_人员姓名", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人员编号 的本地化字符串。
        /// </summary>
        internal static string frmSellers_frmSellers_Load_人员编号 {
            get {
                return ResourceManager.GetString("frmSellers_frmSellers_Load_人员编号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职位 的本地化字符串。
        /// </summary>
        internal static string frmSellers_frmSellers_Load_职位 {
            get {
                return ResourceManager.GetString("frmSellers_frmSellers_Load_职位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取数据库失败! 的本地化字符串。
        /// </summary>
        internal static string frmSellers_frmSellers_Load_读取数据库失败_ {
            get {
                return ResourceManager.GetString("frmSellers_frmSellers_Load_读取数据库失败_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改配置发生错误,错误原因
        ///: 的本地化字符串。
        /// </summary>
        internal static string frmSetting_cmdOK_Click_ {
            get {
                return ResourceManager.GetString("frmSetting_cmdOK_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改配置成功! 的本地化字符串。
        /// </summary>
        internal static string frmSetting_cmdOK_Click_修改配置成功_ {
            get {
                return ResourceManager.GetString("frmSetting_cmdOK_Click_修改配置成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///备注: 的本地化字符串。
        /// </summary>
        internal static string frmSplitDebt_cmdAdd_Click_ {
            get {
                return ResourceManager.GetString("frmSplitDebt_cmdAdd_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加用户分期付款失败! 错误原因: 的本地化字符串。
        /// </summary>
        internal static string frmSplitDebt_cmdAdd_Click_增加用户分期付款失败__错误原因_ {
            get {
                return ResourceManager.GetString("frmSplitDebt_cmdAdd_Click_增加用户分期付款失败__错误原因_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加用户分期付款成功! 的本地化字符串。
        /// </summary>
        internal static string frmSplitDebt_cmdAdd_Click_增加用户分期付款成功_ {
            get {
                return ResourceManager.GetString("frmSplitDebt_cmdAdd_Click_增加用户分期付款成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还款日期: 的本地化字符串。
        /// </summary>
        internal static string frmSplitDebt_cmdAdd_Click_还款日期_ {
            get {
                return ResourceManager.GetString("frmSplitDebt_cmdAdd_Click_还款日期_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除用户分期付款失败! 错误原因: 的本地化字符串。
        /// </summary>
        internal static string frmSplitDebt_cmdDelete_Click_删除用户分期付款失败__错误原因_ {
            get {
                return ResourceManager.GetString("frmSplitDebt_cmdDelete_Click_删除用户分期付款失败__错误原因_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除用户分期付款成功! 的本地化字符串。
        /// </summary>
        internal static string frmSplitDebt_cmdDelete_Click_删除用户分期付款成功_ {
            get {
                return ResourceManager.GetString("frmSplitDebt_cmdDelete_Click_删除用户分期付款成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信用卡 的本地化字符串。
        /// </summary>
        internal static string frmSplitDebt_frmSplitDebt_Load_信用卡 {
            get {
                return ResourceManager.GetString("frmSplitDebt_frmSplitDebt_Load_信用卡", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元 的本地化字符串。
        /// </summary>
        internal static string frmSplitDebt_frmSplitDebt_Load_元 {
            get {
                return ResourceManager.GetString("frmSplitDebt_frmSplitDebt_Load_元", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欠款 的本地化字符串。
        /// </summary>
        internal static string frmSplitDebt_frmSplitDebt_Load_欠款 {
            get {
                return ResourceManager.GetString("frmSplitDebt_frmSplitDebt_Load_欠款", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分期付款的金额超出总额!请检查录入! 确认键将在修改成正确金额后恢复! 的本地化字符串。
        /// </summary>
        internal static string frmSplitDebt_RefreshSplitDebt_分期付款的金额超出总额_请检查录入__确认键将在修改成正确金额后恢复_ {
            get {
                return ResourceManager.GetString("frmSplitDebt_RefreshSplitDebt_分期付款的金额超出总额_请检查录入__确认键将在修改成正确金额后恢复_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取分期付款数据失败! 的本地化字符串。
        /// </summary>
        internal static string frmSplitDebt_RefreshSplitDebt_读取分期付款数据失败_ {
            get {
                return ResourceManager.GetString("frmSplitDebt_RefreshSplitDebt_读取分期付款数据失败_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金额错误 的本地化字符串。
        /// </summary>
        internal static string frmSplitDebt_RefreshSplitDebt_金额错误 {
            get {
                return ResourceManager.GetString("frmSplitDebt_RefreshSplitDebt_金额错误", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除支出记录失败
        /// 的本地化字符串。
        /// </summary>
        internal static string frmViewProfit_cmdDelete_Click_ {
            get {
                return ResourceManager.GetString("frmViewProfit_cmdDelete_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除支出记录成功! 的本地化字符串。
        /// </summary>
        internal static string frmViewProfit_cmdDelete_Click_删除支出记录成功_ {
            get {
                return ResourceManager.GetString("frmViewProfit_cmdDelete_Click_删除支出记录成功_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap keys128 {
            get {
                object obj = ResourceManager.GetObject("keys128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Loging {
            get {
                object obj = ResourceManager.GetObject("Loging", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap order_history128 {
            get {
                object obj = ResourceManager.GetObject("order-history128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ordering128 {
            get {
                object obj = ResourceManager.GetObject("ordering128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap product_sales_report128 {
            get {
                object obj = ResourceManager.GetObject("product-sales-report128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QQ {
            get {
                object obj = ResourceManager.GetObject("QQ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rank_History128 {
            get {
                object obj = ResourceManager.GetObject("Rank-History128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Readcard {
            get {
                object obj = ResourceManager.GetObject("Readcard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reports128 {
            get {
                object obj = ResourceManager.GetObject("reports128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sales_by_Payment_Method_rep128 {
            get {
                object obj = ResourceManager.GetObject("Sales-by-Payment-Method-rep128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sales_report128 {
            get {
                object obj = ResourceManager.GetObject("sales-report128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_database128 {
            get {
                object obj = ResourceManager.GetObject("search-database128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap surveys128 {
            get {
                object obj = ResourceManager.GetObject("surveys128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap taobao {
            get {
                object obj = ResourceManager.GetObject("taobao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tests128 {
            get {
                object obj = ResourceManager.GetObject("tests128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap undo24 {
            get {
                object obj = ResourceManager.GetObject("undo24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Untitled {
            get {
                object obj = ResourceManager.GetObject("Untitled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 未标题_1 {
            get {
                object obj = ResourceManager.GetObject("未标题-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 未标题_11 {
            get {
                object obj = ResourceManager.GetObject("未标题-11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 未标题_12 {
            get {
                object obj = ResourceManager.GetObject("未标题-12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
