//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LongXiangBox.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LongXiangBox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _345 {
            get {
                object obj = ResourceManager.GetObject("345", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ajax_loader {
            get {
                object obj = ResourceManager.GetObject("ajax-loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backcolor {
            get {
                object obj = ResourceManager.GetObject("backcolor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bold {
            get {
                object obj = ResourceManager.GetObject("bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cj {
            get {
                object obj = ResourceManager.GetObject("cj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap color {
            get {
                object obj = ResourceManager.GetObject("color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fj {
            get {
                object obj = ResourceManager.GetObject("fj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似  V 的本地化字符串。
        /// </summary>
        internal static string frmLogin_frmLogin_Load__V {
            get {
                return ResourceManager.GetString("frmLogin_frmLogin_Load__V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其它 的本地化字符串。
        /// </summary>
        internal static string frmMain_cmbAManu_SelectedIndexChanged_其它 {
            get {
                return ResourceManager.GetString("frmMain_cmbAManu_SelectedIndexChanged_其它", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取当前手机信息失败,请重新尝试,错误原因:
        /// 的本地化字符串。
        /// </summary>
        internal static string frmMain_cmbPhone_SelectedIndexChanged_ {
            get {
                return ResourceManager.GetString("frmMain_cmbPhone_SelectedIndexChanged_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除该手机失败! 失败原因:/r/n 的本地化字符串。
        /// </summary>
        internal static string frmMain_cmdDeletePhone_Click_删除该手机失败__失败原因__r_n {
            get {
                return ResourceManager.GetString("frmMain_cmdDeletePhone_Click_删除该手机失败__失败原因__r_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除该手机成功! 的本地化字符串。
        /// </summary>
        internal static string frmMain_cmdDeletePhone_Click_删除该手机成功_ {
            get {
                return ResourceManager.GetString("frmMain_cmdDeletePhone_Click_删除该手机成功_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传成功! 成功添加商品:
        /// 的本地化字符串。
        /// </summary>
        internal static string frmMain_cmdExecute_Click_ {
            get {
                return ResourceManager.GetString("frmMain_cmdExecute_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传失败! 错误原因:
        /// 的本地化字符串。
        /// </summary>
        internal static string frmMain_cmdExecute_Click_Error {
            get {
                return ResourceManager.GetString("frmMain_cmdExecute_Click_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Input Data,Please check them again! 的本地化字符串。
        /// </summary>
        internal static string frmMain_cmdExecute_Click_Error_URL_Please_check_them_again_ {
            get {
                return ResourceManager.GetString("frmMain_cmdExecute_Click_Error_URL_Please_check_them_again_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写具体的手机SEO优化信息! 的本地化字符串。
        /// </summary>
        internal static string frmMain_cmdExecute_Click_请填写具体的手机SEO优化信息_ {
            get {
                return ResourceManager.GetString("frmMain_cmdExecute_Click_请填写具体的手机SEO优化信息_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写具体的手机信息! 的本地化字符串。
        /// </summary>
        internal static string frmMain_cmdExecute_Click_请填写具体的手机信息_ {
            get {
                return ResourceManager.GetString("frmMain_cmdExecute_Click_请填写具体的手机信息_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写具体的手机配置信息! 的本地化字符串。
        /// </summary>
        internal static string frmMain_cmdExecute_Click_请填写具体的手机配置信息_ {
            get {
                return ResourceManager.GetString("frmMain_cmdExecute_Click_请填写具体的手机配置信息_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机 龙翔 手机报价 手机大全 手机评测 龙翔评测 龙翔报价  的本地化字符串。
        /// </summary>
        internal static string frmMain_cmdKWordsPaste_Click_手机_龙翔_手机报价_手机大全_手机评测_龙翔评测_龙翔报价_ {
            get {
                return ResourceManager.GetString("frmMain_cmdKWordsPaste_Click_手机_龙翔_手机报价_手机大全_手机评测_龙翔评测_龙翔报价_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Version: 的本地化字符串。
        /// </summary>
        internal static string frmMain_frmMain_Load__Version_ {
            get {
                return ResourceManager.GetString("frmMain_frmMain_Load__Version_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not open Mysql Connection,Check your Network Connection or BoxSetting.ini 的本地化字符串。
        /// </summary>
        internal static string frmMain_frmMain_Load_Can_not_open_Mysql_Connection_Check_your_Network_Connection_or_BoxSetting_ini {
            get {
                return ResourceManager.GetString("frmMain_frmMain_Load_Can_not_open_Mysql_Connection_Check_your_Network_Connection_" +
                        "or_BoxSetting_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Network Connected! 的本地化字符串。
        /// </summary>
        internal static string frmMain_frmMain_Load_No_Network_Connected_ {
            get {
                return ResourceManager.GetString("frmMain_frmMain_Load_No_Network_Connected_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JPEG FILE|*.jpg 的本地化字符串。
        /// </summary>
        internal static string frmPhotos_cmdMain_Click_JPEG_FILE___jpg {
            get {
                return ResourceManager.GetString("frmPhotos_cmdMain_Click_JPEG_FILE___jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Main Photo of Phone 的本地化字符串。
        /// </summary>
        internal static string frmPhotos_cmdMain_Click_Select_Main_Photo_of_Phone {
            get {
                return ResourceManager.GetString("frmPhotos_cmdMain_Click_Select_Main_Photo_of_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Photos of Phone 的本地化字符串。
        /// </summary>
        internal static string frmPhotos_cmdPhotos_Click_Select_Photos_of_Phone {
            get {
                return ResourceManager.GetString("frmPhotos_cmdPhotos_Click_Select_Photos_of_Phone", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap indent {
            get {
                object obj = ResourceManager.GetObject("indent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap italic {
            get {
                object obj = ResourceManager.GetObject("italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap link {
            get {
                object obj = ResourceManager.GetObject("link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lj {
            get {
                object obj = ResourceManager.GetObject("lj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Loging {
            get {
                object obj = ResourceManager.GetObject("Loging", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ol {
            get {
                object obj = ResourceManager.GetObject("ol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap outdent {
            get {
                object obj = ResourceManager.GetObject("outdent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rj {
            get {
                object obj = ResourceManager.GetObject("rj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap underscore {
            get {
                object obj = ResourceManager.GetObject("underscore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap uol {
            get {
                object obj = ResourceManager.GetObject("uol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败! 错误原因
        /// 的本地化字符串。
        /// </summary>
        internal static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新成功! 成功更新商品:
        /// 的本地化字符串。
        /// </summary>
        internal static string UpdateOK {
            get {
                return ResourceManager.GetString("UpdateOK", resourceCulture);
            }
        }
    }
}
